name: Escaneo diario de precios

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  escanear:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4 psycopg2-binary
      - name: Verificar variable
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: echo $DATABASE_URL | sed 's/:.*@/:***@/'
      - name: Correr scheduler
        env:
          DATABASE_URL:   ${{ secrets.DATABASE_URL }}
          GMAIL_USUARIO:  ${{ secrets.GMAIL_USUARIO }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}

          
        run: python scheduler.py
